# Default values for assistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# app 
appService:
  - name: spider
    port: 0
    replicaCount: 1
    owner: tsundata
  - name: cron
    port: 0
    replicaCount: 1
    owner: tsundata
  - name: gateway
    port: 5000
    replicaCount: 1
    owner: tsundata
  - name: chatbot
    port: 6000
    replicaCount: 1
    owner: tsundata
  - name: message
    port: 6001
    replicaCount: 1
    owner: tsundata
  - name: middle
    port: 6002
    replicaCount: 1
    owner: tsundata
  - name: user
    port: 6004
    replicaCount: 1
    owner: tsundata
  - name: storage
    port: 6009
    replicaCount: 1
    owner: tsundata
  - name: task
    port: 6010
    replicaCount: 1
    owner: tsundata
  - name: id
    port: 6012
    replicaCount: 1
    owner: tsundata
  - name: web
    port: 7000
    replicaCount: 1
    owner: sysatom
    version: "0.0.1-1-g80b6296"

# etcd config
etcd:
  address: ""
  username: ""
  password: ""

# tls config
tls:
  crt: ""
  key: ""

# domain config
domain:
  gateway: ""
  web: ""
