apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
  namespace: {{ $.Chart.Name }}
data:
  etcd.address: {{ $.Values.etcd.address }}
  etcd.username: {{ $.Values.etcd.username }}
  etcd.password: {{ $.Values.etcd.password }}
