{{- range $i, $val := $.Values.appService }}
{{- if gt (int (toString ($val.port))) 0 }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Chart.Name }}
  name: {{ $val.name }}
spec:
  ports:
    - name: http
      port: {{ $val.port }}
      protocol: TCP
      targetPort: {{ $val.port }}
  selector:
    app: {{ $val.name }}
  sessionAffinity: ClientIP
  type: ClusterIP
---
{{ end -}}
{{ end -}}
