apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
  namespace: {{ $.Chart.Name }}
data:
  etcd.address: {{ .Files.Get "etcd.address.val" }}
  etcd.username: {{ .Files.Get "etcd.username.val" }}
  etcd.password: {{ .Files.Get "etcd.password.val" }}
