{{- range $i, $val := $.Values.appService }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $val.name }}
  namespace: {{ $.Chart.Name }}
spec:
  replicas: {{ $val.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      containers:
        - name: {{ $val.name }}
          image: "ghcr.io/{{ $val.owner }}/{{ $val.name }}:v{{ if $val.version }}{{ $val.version }}{{ else }}{{ $.Chart.AppVersion }}{{ end }}"
          imagePullPolicy: Always
          env:
            - name: ETCD_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.address
            - name: ETCD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.username
            - name: ETCD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: etcd-config
                  key: etcd.password
          {{- if gt (int (toString ($val.port))) 0 }}
          ports:
            - containerPort: {{ $val.port }}
          {{- end }}
---
{{ end -}}
