apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ $.Chart.Name }}
spec:
  rules:
    - host: {{ .Values.domain.gateway }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 5000
    - host: {{ .Values.domain.web }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 7000
  tls:
    - hosts:
        - {{ .Values.domain.gateway }}
        - {{ .Values.domain.web }}
      secretName: {{ $.Chart.Name }}-tls
